=== Petit-Chaperon-Rouge/TPs_XML/src/notes.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="notes" type="t_notes" />

    <xs:complexType name="t_notes">
        <xs:sequence>
            <xs:element name="note" type="t_note" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="t_note">
        <xs:sequence>
            <xs:element name="title" type="xs:string" />
            <xs:element name="message" type="xs:string" />
            <xs:element name="from" type="xs:string" />
            <xs:element name="to" type="xs:string" />
            <xs:element name="read" type="t_read" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="color" type="t_color" />
        <xs:attribute name="date" type="xs:date" />
    </xs:complexType>

    <xs:simpleType name="t_color">
        <xs:restriction base="xs:string">
            <xs:enumeration value="yellow" />
            <xs:enumeration value="pink" />
            <xs:enumeration value="cyan" />
            <xs:enumeration value="green" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="t_read">
        <xs:sequence />
    </xs:complexType>
</xs:schema>

=== Petit-Chaperon-Rouge/TPs_XML/src/notes.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
<!DOCTYPE notes [
        <!ELEMENT notes (note*)>
        <!ATTLIST note date CDATA #REQUIRED>
        <!ATTLIST note color (yellow|pink|cyan|green) #REQUIRED>
        <!ELEMENT note (title, message, from, to, read?)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT message (#PCDATA)>
        <!ELEMENT from (#PCDATA)>
        <!ELEMENT to (#PCDATA)>
        <!ELEMENT read EMPTY>
]>
-->

<notes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="notes.xsd">
    <note date="2019-01-21" color="yellow">
        <title>N'oublie pas !</title>
        <message>Pense à sortir le chat...</message>
        <from>Bob</from>
        <to>Alice</to>
        <read/>
    </note>
    <note date="2019-01-22" color="pink">
        <title>Pas le temps</title>
        <message>Fais le toi-même !</message>
        <from>Alice</from>
        <to>Bob</to>
        <read/>
    </note>
    <note date="2019-01-22" color="cyan">
        <title>Oops !</title>
        <message>Ça marche plus...</message>
        <from>Noob</from>
        <to>Dev</to>
    </note>
</notes>
